game: Starcraft 2
name: StarcraftAlpha
Starcraft 2:
  progression_balancing: 50
  accessibility: items
  game_difficulty: normal
  game_speed: faster
  disable_forced_camera: 'false'
  skip_cutscenes: 'true'
  all_in_map: air
  mission_order: vanilla_shuffled
  maximum_campaign_size: 83
  grid_two_start_positions: 'false'
  player_color_terran_raynor: random
  player_color_protoss: random
  player_color_zerg: random
  player_color_zerg_primal: random
  enable_wol_missions: 'true'
  enable_prophecy_missions: 'false'
  enable_hots_missions: 'true'
  enable_lotv_prologue_missions: 'false'
  enable_lotv_missions: 'true'
  enable_epilogue_missions: 'true'
  enable_nco_missions: 'false'
  shuffle_campaigns: 'false'
  shuffle_no_build: 'false'
  starter_unit: random
  required_tactics: standard
  ensure_generic_items: 100
  min_number_of_upgrades: 2
  max_number_of_upgrades: -1
  generic_upgrade_missions: 25
  generic_upgrade_research: always_auto
  generic_upgrade_items: individual_items
  kerrigan_presence: vanilla
  kerrigan_levels_per_mission_completed: 0
  kerrigan_levels_per_mission_completed_cap: -1
  kerrigan_level_item_sum: 0
  kerrigan_level_item_distribution: size_1
  kerrigan_total_level_cap: -1
  start_primary_abilities: 0
  kerrigan_primal_status: always_zerg
  spear_of_adun_presence: lotv_protoss
  spear_of_adun_present_in_no_build: 'false'
  spear_of_adun_autonomously_cast_ability_presence: lotv_protoss
  spear_of_adun_autonomously_cast_present_in_no_build: 'false'
  grant_story_tech: 'false'
  grant_story_levels: minimum
  take_over_ai_allies: 'false'
  excluded_items:
    - Ability
  excluded_missions: []
  exclude_very_hard_missions: default
  nco_items: 'true'
  bw_items: 'true'
  ext_items: 'true'
  vanilla_locations: enabled
  extra_locations: enabled
  challenge_locations: enabled
  mastery_locations: enabled
  minerals_per_item: 20
  vespene_per_item: 20
  starting_supply_per_item: 5
  start_inventory:
    Spawn Banelings (Kerrigan Tier 4): 1
    Ability Efficiency (Kerrigan Tier 6): 1
  plando_items:
    - item:
        Quatro: 1
      location: 'Evacuation: Secret Resource Stash'
      from_pool: true
      world: false
  protoss_units:
    Aiur: 1
    Nerazim: 1
    Purifier: 1
    Tal'Darim: 1

triggers:
  #Aiur faction only
  - option_name: protoss_units
    option_category: Starcraft 2
    option_result: Aiur
    options:
      Starcraft 2:
        player_color_protoss:
          teal: 50
        +excluded_items:
          - Purifier
          - Nerazim
          - Tal'Darim

  #Nerazim faction only
  - option_name: protoss_units
    option_category: Starcraft 2
    option_result: Nerazim
    options:
      Starcraft 2:
        player_color_protoss:
          purple: 50
        +excluded_items:
          - Purifier
          - Aiur
          - Tal'Darim

  #Purifier faction only
  - option_name: protoss_units
    option_category: Starcraft 2
    option_result: Purifier
    options:
      Starcraft 2:
        player_color_protoss:
          orange: 50
        +excluded_items:
          - Aiur
          - Nerazim
          - Tal'Darim

  #Tal'Darim faction only
  - option_name: protoss_units
    option_category: Starcraft 2
    option_result: Tal'Darim
    options:
      Starcraft 2:
        player_color_protoss:
          red: 50
        +excluded_items:
          - Purifier
          - Nerazim
          - Aiur