# This file has to be in the Players folder to take effect, keeping the "meta.yaml" name
# A meta file rolls its own set of options first
# The result will then overwrite each player's option in that particular field
# For example, if a meta.yaml fast_ganon result is rolled, every player will have that fast_ganon goal
# There is the special case of null, which ignores that part of the meta.yaml,
# allowing for a chance for that meta to not take effect
meta_description: Meta-Mystery file with the intention of having similar-length completion times for a hopefully better experience
null:
  progression_balancing: 10
  accessibility: items
